const router = [
  {
    children: [
      {
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'home-3-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/platform_overview',
          hidden: false,
          icon: 'home-3-fill',
          isCustomSvg: false,
          noClosable: true,
          noKeepAlive: true,
          redirect: '',
          tabHidden: false,
          title: '总控台',
        },
        name: 'Workbench',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'zjRYRFGXzk',
        orderBy: 11,
        parent: 'SVoMYPK8D5',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/index',
      },
    ],
    createdAt: '2021-08-11T11:21:52.740Z',
    icon: 'home-3-fill',
    meta: {
      alwaysShow: false,
      badge: '',
      component: 'Layout',
      hidden: false,
      icon: 'home-2-line',
      isCustomSvg: false,
      noClosable: true,
      noKeepAlive: true,
      redirect: '/index',
      tabHidden: false,
      title: '总控台',
    },
    name: 'Dashboard',
    navShow: [{ alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' }],
    objectId: 'SVoMYPK8D5',
    orderBy: 1,
    parent: '0',
    updatedAt: '2021-08-11T11:21:52.740Z',
    url: '/',
  },
  {
    ACL: {
      '*': { read: true, write: true },
      'role:admin': { read: true, write: true },
    },
    children: [
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'product-hunt-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/home_group2',
          hidden: false,
          icon: 'product-hunt-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '产品管理',
        },
        name: 'ProductManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '19d5222fb5',
        orderBy: 21,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/dashboard/productlist',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'exchange-box-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/engine/home_resourcechannel',
          hidden: false,
          icon: 'exchange-box-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '通道管理',
        },
        name: 'ChannelManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '113bfa31f4',
        orderBy: 22,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/dashboard/resourcechannel',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'device-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/home_index',
          hidden: false,
          icon: 'device-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '设备管理',
        },
        name: 'EquipmentManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'cfda8d3366',
        orderBy: 23,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/dashboard/devicelist',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'temp-hot-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/profile',
          hidden: false,
          icon: 'temp-hot-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '设备模板',
        },
        name: 'EquipmentTemplate',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '3760d5c787',
        orderBy: 25,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/dashboard/profile',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'building-4-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/engine/dict',
          hidden: false,
          icon: 'building-4-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '字典管理',
        },
        name: 'DictionaryManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'e32799936a',
        orderBy: 26,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/dashboard/dict',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'bug-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/onlinetest',
          hidden: false,
          icon: 'bug-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '在线调试',
        },
        name: 'OnlineDebugging',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'a2b950dcbe',
        orderBy: 26,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/roles/onlinetest',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'bike-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/topo/VueKonva',
          hidden: true,
          icon: 'bike-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '组态大屏',
        },
        name: 'GetScreenConfigurationAccessor',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '92717b489e',
        orderBy: 27,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/Topo/VueKonva',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'bar-chart-horizontal-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/engine/createResourcechannel',
          hidden: true,
          icon: 'bar-chart-horizontal-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '创建通道',
        },
        name: 'CreateResourcechannel',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '09036ec2fd',
        orderBy: 221,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/CreateResourcechannel',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'home-3-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/editdevices',
          hidden: true,
          icon: 'home-3-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '设备详情',
        },
        name: 'EquipmentDetails',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '14af7cd9b8',
        orderBy: 231,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/roles/editdevices',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'device-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/index',
          hidden: true,
          icon: 'device-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '子设备管理',
        },
        name: 'ChildDeviceManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'd9b7460440',
        orderBy: 232,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/roles/thing',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'video-add-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/tools/player',
          hidden: true,
          icon: 'video-add-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '视频播放器',
        },
        name: 'VideoPlayer',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '18c6a4a9bf',
        orderBy: 233,
        parent: '8f821711e1',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/tools/player',
      },
    ],
    createdAt: '2021-08-11T11:21:52.740Z',
    icon: 'product-hunt-fill',
    meta: {
      alwaysShow: false,
      badge: '',
      component: 'Layout',
      hidden: false,
      icon: 'product-hunt-fill',
      isCustomSvg: false,
      noClosable: false,
      noKeepAlive: false,
      redirect: '/dashboard/productlist',
      tabHidden: false,
      title: ' 设备云',
    },
    name: 'EquipmentCloud',
    navShow: [{ alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' }],
    objectId: '8f821711e1',
    orderBy: 2,
    parent: '0',
    updatedAt: '2021-08-11T11:21:52.740Z',
    url: '/dashboard',
  },
  {
    ACL: {
      '*': { read: true, write: true },
      'role:admin': { read: true, write: true },
    },
    children: [
      {
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'usermanage',
        meta: {
          component: '@/views/roles/structure',
          icon: 'shopping-cart-line',
          title: '用户管理',
        },
        name: 'Structure',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'dsnf1u9vCx',
        orderBy: 31,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/structures',
      },
      {
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'menu',
        meta: {
          component: '@/views/roles/menu',
          icon: 'menu-2-fill',
          title: '菜单管理',
        },
        name: 'Menu',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'ECsbqM3di4',
        orderBy: 32,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/roles/menu',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'shield-user-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/roles/rolelist/roles',
          hidden: false,
          icon: 'shield-user-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '角色管理',
        },
        name: 'RoleManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '2a0b2eed09',
        orderBy: 33,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/roles/roles',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'open-arm-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/roles/rolelist/rolescontrol',
          hidden: false,
          icon: 'open-arm-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '接口管理',
        },
        name: 'SetManagementInterface',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'cc40a5c2bc',
        orderBy: 34,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/roles/rolescontrol',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'apple-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/appOperate/application',
          hidden: false,
          icon: 'apple-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '应用管理',
        },
        name: 'ApplicationManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '760cb0f88e',
        orderBy: 35,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/roles/applicationManagement',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'luggage-deposit-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/roles/department/department',
          hidden: false,
          icon: 'luggage-deposit-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '岗位管理',
        },
        name: 'PostManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '0512201918',
        orderBy: 35,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/department',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'sound-module-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/systemmanage/modules',
          hidden: true,
          icon: 'sound-module-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '模板管理',
        },
        name: 'TemplateManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '54c68e3992',
        orderBy: 37,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/modules',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'apps-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/appOperate/addApp',
          hidden: true,
          icon: 'apps-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '新增应用',
        },
        name: 'NewApplication',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '6a656efa55',
        orderBy: 38,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/applicationManagement/addApp',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'device-recover-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/group',
          hidden: true,
          icon: 'device-recover-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '设备管理',
        },
        name: 'EquipmentManagementCenter',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '81039c30eb',
        orderBy: 39,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/roles/group',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'user-2-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/user/userinfo',
          hidden: true,
          icon: 'user-2-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '用户中心',
        },
        name: 'UserCenter',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '1b6fba6483',
        orderBy: 301,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/userinfo',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'edit-box-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/roles/adduser/edituser',
          hidden: true,
          icon: 'edit-box-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '编辑用户',
        },
        name: 'UserSetEditorKit',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'c752ff5c3d',
        orderBy: 302,
        parent: '2f2867fa49',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/roles/edituser',
      },
    ],
    createdAt: '2021-08-11T11:21:52.740Z',
    icon: 'admin-fill',
    meta: {
      alwaysShow: false,
      badge: '',
      component: 'Layout',
      hidden: false,
      icon: 'admin-fill',
      isCustomSvg: false,
      noClosable: false,
      noKeepAlive: false,
      redirect: '/structures',
      tabHidden: false,
      title: '多租户',
    },
    name: 'Multitenant',
    navShow: [{ alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' }],
    objectId: '2f2867fa49',
    orderBy: 3,
    parent: '0',
    updatedAt: '2021-08-11T11:21:52.740Z',
    url: '/roles',
  },
  {
    ACL: {
      '*': { read: true, write: true },
      'role:admin': { read: true, write: true },
    },
    children: [
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'file-chart-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/Maintenance/index',
          hidden: false,
          icon: 'file-chart-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '所有工单',
        },
        name: 'AllWorkOrder',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'e5f165661c',
        orderBy: 41,
        parent: 'ee1042a17e',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/CloudOt/index',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'task-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/Maintenance/myticket',
          hidden: false,
          icon: 'task-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '我的工单',
        },
        name: 'MyWorkOrder',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '75763f7ad1',
        orderBy: 42,
        parent: 'ee1042a17e',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/CloudOt/myticket',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'alarm-warning-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/Maintenance/alert',
          hidden: false,
          icon: 'alarm-warning-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '告警中心',
        },
        name: 'Alarm',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'a0fdfba6cd',
        orderBy: 43,
        parent: 'ee1042a17e',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/CloudOt/alarm',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.740Z',
        icon: 'creative-commons-by-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/Maintenance/createTicket',
          hidden: false,
          icon: 'creative-commons-by-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '创建工单',
        },
        name: 'CreateWorkOrder',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'e2bb0e7dc8',
        orderBy: 44,
        parent: 'ee1042a17e',
        updatedAt: '2021-08-11T11:21:52.740Z',
        url: '/CloudOt/createTicket',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'home-3-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/Maintenance/processTicket',
          hidden: false,
          icon: 'mini-program-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '处理工单',
        },
        name: 'HandleRepairOrder',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '718ca9c223',
        orderBy: 45,
        parent: 'ee1042a17e',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/CloudOt/ProcessTicket',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'compass-discover-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/Maintenance/dispatchTicket',
          hidden: false,
          icon: 'compass-discover-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '派发工单',
        },
        name: 'DistributeWorkOrders',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '07e46af052',
        orderBy: 46,
        parent: 'ee1042a17e',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/CloudOt/dispatchTicket',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'calendar-event-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/Maintenance/evaluationTicket',
          hidden: false,
          icon: 'calendar-event-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '结束工单',
        },
        name: 'EndOfRepairOrder',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '8ac5e547c0',
        orderBy: 47,
        parent: 'ee1042a17e',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/CloudOt/EvaluationTicket',
      },
    ],
    createdAt: '2021-08-11T11:21:52.740Z',
    icon: 'cloud-fill',
    meta: {
      alwaysShow: false,
      badge: '',
      component: 'Layout',
      hidden: false,
      icon: 'cloud-fill',
      isCustomSvg: false,
      noClosable: false,
      noKeepAlive: false,
      redirect: '/CloudOt/index',
      tabHidden: false,
      title: '云运维',
    },
    name: 'CloudOperations',
    navShow: [{ alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' }],
    objectId: 'ee1042a17e',
    orderBy: 4,
    parent: '0',
    updatedAt: '2021-08-11T11:21:52.740Z',
    url: '/CloudOt',
  },
  {
    ACL: {
      '*': { read: true, write: true },
      'role:admin': { read: true, write: true },
    },
    children: [
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'file-word-2-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component:
            '@/views/equipment_management/appOperate/applicationManagement',
          hidden: false,
          icon: 'file-word-2-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '工程管理',
        },
        name: 'EngineeringManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'c219d5b111',
        orderBy: 51,
        parent: '4c6c8c5b59',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/roles/projectManagement',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'mini-program-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/systemmanage/expandprogram',
          hidden: false,
          icon: 'mini-program-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '扩展编程',
        },
        name: 'ExtendedProgramming',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '3f24a349f1',
        orderBy: 52,
        parent: '4c6c8c5b59',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/dashboard/expandprogram',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'code-box-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/thingsParse',
          hidden: false,
          icon: 'code-box-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '解码管理',
        },
        name: 'DecodingManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '0ae2d28d46',
        orderBy: 53,
        parent: '4c6c8c5b59',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/roles/thingsParse',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'ruler-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/engine/rulesengine',
          hidden: false,
          icon: 'ruler-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '规则管理',
        },
        name: 'RuleManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '930bfe41f0',
        orderBy: 54,
        parent: '4c6c8c5b59',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/rules_engine/engine',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'mail-add-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/engine/addengine',
          hidden: true,
          icon: 'mail-add-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '添加规则',
        },
        name: 'AddRules',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '2261f5a8e9',
        orderBy: 541,
        parent: '4c6c8c5b59',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/rules_engine/addengine',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'eye-2-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/engine/checkengine',
          hidden: true,
          icon: 'eye-2-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '查看规则',
        },
        name: 'ViewRules',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '70549bcc94',
        orderBy: 542,
        parent: '4c6c8c5b59',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/rules_engine/checkengine',
      },
    ],
    createdAt: '2021-08-11T11:21:52.740Z',
    icon: 'team-fill',
    meta: {
      alwaysShow: false,
      badge: '',
      component: 'Layout',
      hidden: false,
      icon: 'team-fill',
      isCustomSvg: false,
      noClosable: false,
      noKeepAlive: false,
      redirect: '/roles/projectManagement',
      tabHidden: false,
      title: ' 云函数',
    },
    name: 'CloudFunction',
    navShow: [{ alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' }],
    objectId: '4c6c8c5b59',
    orderBy: 5,
    parent: '0',
    updatedAt: '2021-08-11T11:21:52.740Z',
    url: '/base',
  },
  {
    ACL: {
      '*': { read: true, write: true },
      'role:admin': { read: true, write: true },
    },
    children: [
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'video-chat-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/dashboard/index',
          hidden: false,
          icon: 'video-chat-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '性能监控',
        },
        name: 'PerformanceMonitoring',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '3f0335d72a',
        orderBy: 61,
        parent: '9405b9d9b9',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/performance_monitoring',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'plug-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/systemmanage/appmarage',
          hidden: false,
          icon: 'plug-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '插件管理',
        },
        name: 'Plug_inManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '434556128e',
        orderBy: 62,
        parent: '9405b9d9b9',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/roles/appmanage',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'group-2-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/installation/log',
          hidden: false,
          icon: 'group-2-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '集群管理',
        },
        name: 'UnableToResolveModClusterManagementHost',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'a4f99a0ef1',
        orderBy: 63,
        parent: '9405b9d9b9',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/roles/nodes',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'codepen-line',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/server_control',
          hidden: false,
          icon: 'codepen-line',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '部署管理',
        },
        name: 'DeploymentManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: '7135d51e09',
        orderBy: 64,
        parent: '9405b9d9b9',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/roles/server_control',
      },
      {
        ACL: {
          '*': { read: true, write: true },
          'role:admin': { read: true, write: true },
        },
        createdAt: '2021-08-11T11:21:52.739Z',
        icon: 'parking-box-fill',
        meta: {
          alwaysShow: false,
          badge: '',
          component: '@/views/equipment_management/parse',
          hidden: false,
          icon: 'parking-box-fill',
          isCustomSvg: false,
          noClosable: false,
          noKeepAlive: false,
          redirect: '',
          tabHidden: false,
          title: '数据管理',
        },
        name: 'DataManagement',
        navShow: [
          { alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' },
        ],
        objectId: 'c33ff3817d',
        orderBy: 65,
        parent: '9405b9d9b9',
        updatedAt: '2021-08-11T11:21:52.739Z',
        url: '/dashboard/parse',
      },
    ],
    createdAt: '2021-08-11T11:21:52.739Z',
    icon: 'closed-captioning-line',
    meta: {
      alwaysShow: false,
      badge: '',
      component: 'Layout',
      hidden: false,
      icon: 'closed-captioning-line',
      isCustomSvg: false,
      noClosable: false,
      noKeepAlive: false,
      redirect: '/performance_monitoring',
      tabHidden: false,
      title: '云系统',
    },
    name: 'CloudSystem',
    navShow: [{ alias: '系统管理员', roleId: 'CUgndqoYDy', roleName: 'admin' }],
    objectId: '9405b9d9b9',
    orderBy: 6,
    parent: '0',
    updatedAt: '2021-08-11T11:21:52.739Z',
    url: '/dashboard/expandprogram',
  },
]
export default router
