# Generated oilfield thing model additions
    "oilfield_g1": {
        "product_name": "8路AI，4路DI (G1)",
        "points": {
            "g1_oil_pressure": {
                "name": "油压",
                "unit": "MPa",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d6c",
            },
            "g1_casing_pressure": {
                "name": "套压",
                "unit": "MPa",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d6e",
            },
            "g1_back_pressure": {
                "name": "回压",
                "unit": "MPa",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d70",
            },
            "g1_wellhead_oil_temp": {
                "name": "井口油温",
                "unit": "℃",
                "type": "float32",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x9d72",
            },
            "g1_suspension_load": {
                "name": "当前悬点载荷",
                "unit": "KN",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d74",
            },
            "g1_displacement": {
                "name": "位移",
                "unit": "m",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d76",
            },
            "g1_ai7_custom": {
                "name": "AI7，自定义",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d78",
            },
            "g1_ai8_custom": {
                "name": "AI8，自定义",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d7a",
            },
            "g1_power_device_manual_auto": {
                "name": "动力设备手/自动状态",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d7c",
            },
            "g1_power_device_running_status": {
                "name": "动力设备运行状态",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9d7d",
            },
            "g1_di3_status": {
                "name": "DI3状态",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9d7e",
            },
            "g1_di4_status": {
                "name": "DI4状态",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9d7f",
            },
            "g1_power_device_start_stop_ctrl": {
                "name": "动力设备启停控制",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d80",
            },
            "g1_power_device_start_alarm_delay": {
                "name": "动力设备启动报警延时时间",
                "unit": "min",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9d81",
            },
            "g1_active_wakeup_flag": {
                "name": "主动唤醒标识",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d82",
            },
            "g1_do4": {
                "name": "DO4",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d83",
            },
            "g1_dynamic_liquid_level": {
                "name": "动液面深度",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d84",
            },
            "g1_dynamic_liquid_pressure": {
                "name": "动液面套压",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d85",
            },
            "g1_temperature_1_wpc": {
                "name": "温度1（温压一体表）",
                "unit": "℃",
                "type": "float32",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x9d86",
            },
            "g1_temperature_2_wpc": {
                "name": "温度2（温压一条表）",
                "unit": "℃",
                "type": "float32",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x9d88",
            },
            "g1_ai0": {
                "name": "AI0",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d8a",
            },
            "g1_ai1": {
                "name": "AI1",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d8c",
            },
            "g1_ai2": {
                "name": "AI2",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d8e",
            },
            "g1_ai3": {
                "name": "AI3",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d90",
            },
            "g1_ai4": {
                "name": "AI4",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d92",
            },
            "g1_ai5": {
                "name": "AI5",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d94",
            },
        }
    },
    "oilfield_g2": {
        "product_name": "电参 (G2)",
        "points": {
            "g2_motor_current_a": {
                "name": "电机工作电流A相",
                "unit": "A",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9d9f",
            },
            "g2_motor_current_b": {
                "name": "电机工作电流B相",
                "unit": "A",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9da1",
            },
            "g2_motor_current_c": {
                "name": "电机工作电流C相",
                "unit": "A",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9da3",
            },
            "g2_motor_voltage_a": {
                "name": "电机工作电压A相",
                "unit": "V",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9da5",
            },
            "g2_motor_voltage_b": {
                "name": "电机工作电压B相",
                "unit": "V",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9da7",
            },
            "g2_motor_voltage_c": {
                "name": "电机工作电压C相",
                "unit": "V",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9da9",
            },
            "g2_motor_active_energy": {
                "name": "电机有功功耗",
                "unit": "KW·h",
                "type": "float32",
                "category": "energy",
                "min": 0, "max": 9999,
                "register_addr": "0x9dab",
            },
            "g2_motor_reactive_energy": {
                "name": "电机无功功耗",
                "unit": "KW·h",
                "type": "float32",
                "category": "energy",
                "min": 0, "max": 9999,
                "register_addr": "0x9dad",
            },
            "g2_motor_active_power": {
                "name": "电机有功功率",
                "unit": "KW",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9daf",
            },
            "g2_motor_reactive_power": {
                "name": "电机无功功率",
                "unit": "KW",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9db1",
            },
            "g2_motor_reverse_power": {
                "name": "电机反向功率",
                "unit": "KW",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9db3",
            },
            "g2_motor_power_factor": {
                "name": "电机功率因数",
                "unit": "实型",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9db5",
            },
            "g2_total_energy": {
                "name": "总功耗",
                "unit": "KW·h",
                "type": "float32",
                "category": "energy",
                "min": 0, "max": 9999,
                "register_addr": "0x9db7",
            },
            "g2_temporary_total_energy": {
                "name": "零时总功耗",
                "unit": "KW·h",
                "type": "float32",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x9dcb",
            },
            "g2_daily_energy": {
                "name": "日耗电量",
                "unit": "KW·h",
                "type": "float32",
                "category": "energy",
                "min": 0, "max": 9999,
                "register_addr": "0x9dcd",
            },
        }
    },
    "oilfield_g3": {
        "product_name": "变频参数 (G3)",
        "points": {
            "g3_motor_operation_mode": {
                "name": "电机运行模式",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9dd0",
            },
            "g3_frequency_control_mode": {
                "name": "频率控制方式",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9dd1",
            },
            "g3_vfd_set_frequency": {
                "name": "变频设置频率",
                "unit": "Hz",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9dd2",
            },
            "g3_vfd_running_frequency": {
                "name": "变频运行频率",
                "unit": "Hz",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9dd4",
            },
            "g3_vfd_fault_status": {
                "name": "变频故障状态",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9dd6",
            },
        }
    },
    "oilfield_g4": {
        "product_name": "抽油机特有参数 (G4)",
        "points": {
            "g4_stroke_freq": {
                "name": "冲次",
                "unit": "次/min",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9de4",
            },
            "g4_stroke_length": {
                "name": "冲程",
                "unit": "m",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9de6",
            },
        }
    },
    "oilfield_g5": {
        "product_name": "螺杆泵特有参数 (G5)",
        "points": {
            "g5_rotation_speed": {
                "name": "转速",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9dee",
            },
            "g5_torque": {
                "name": "扭矩",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9df0",
            },
        }
    },
    "oilfield_g6": {
        "product_name": "报警故障诊断 (G6)",
        "points": {
            "g6_terminal_status_reg_1": {
                "name": "终端自身状态寄存1",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9df8",
            },
            "g6_terminal_status_reg_2": {
                "name": "终端自身状态寄存2",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9df9",
            },
            "g6_ai_instrument_fault_1": {
                "name": "AI仪表故障码1",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9dfa",
            },
            "g6_ai_instrument_fault_2": {
                "name": "AI仪表故障码2",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9dfb",
            },
            "g6_ai_alarm_code_1": {
                "name": "AI报警码1",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9dfc",
            },
            "g6_ai_alarm_code_2": {
                "name": "AI报警码2",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9dfd",
            },
            "g6_di_alarm_code": {
                "name": "DI报警码",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x9dfe",
            },
            "g6_power_device_stop_reason": {
                "name": "动力设备停机原因",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9dff",
            },
            "g6_power_device_start_reason": {
                "name": "动力设备开机原因",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e00",
            },
            "alarm_id": {
                "name": "告警ID",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0",
            },
        }
    },
    "oilfield_g7": {
        "product_name": "仪表扩展 (G7)",
        "points": {
            "g7_pressure0_comm_efficiency": {
                "name": "压力表0通信效率",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_pressure0_battery_voltage": {
                "name": "压力表0电池电压",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_pressure0_sleep_time": {
                "name": "压力表0休眠时间",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_pressure0_status": {
                "name": "压力表0仪表状态",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_pressure0_value": {
                "name": "压力表0压力值",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_pressure0_battery_remain": {
                "name": "压力表0电池剩余时间",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_pressure0_work_temperature": {
                "name": "压力表0工作温度",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_pressure1_comm_efficiency": {
                "name": "压力表1通信效率",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_pressure1_battery_voltage": {
                "name": "压力表1电池电压",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_pressure1_sleep_time": {
                "name": "压力表1休眠时间",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_pressure1_status": {
                "name": "压力表1仪表状态",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_pressure1_value": {
                "name": "压力表1压力值",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_pressure1_battery_remain": {
                "name": "压力表1电池剩余时间",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_pressure1_work_temperature": {
                "name": "压力表1工作温度",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_pressure2_comm_efficiency": {
                "name": "压力表2通信效率",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_pressure2_battery_voltage": {
                "name": "压力表2电池电压",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_pressure2_sleep_time": {
                "name": "压力表2休眠时间",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_pressure2_status": {
                "name": "压力表2仪表状态",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_pressure2_value": {
                "name": "压力表2压力值",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_pressure2_battery_remain": {
                "name": "压力表2电池剩余时间",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_pressure2_work_temperature": {
                "name": "压力表2工作温度",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_temp0_comm_efficiency": {
                "name": "温度表0通信效率",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_temp0_battery_voltage": {
                "name": "温度表0电池电压",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_temp0_sleep_time": {
                "name": "温度表0休眠时间",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_temp0_status": {
                "name": "温度表0仪表状态",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_temp0_value": {
                "name": "温度表0温度值",
                "unit": "",
                "type": "float32",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_temp0_battery_remain": {
                "name": "温度表0电池剩余时间",
                "unit": "",
                "type": "float32",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_temp0_work_temperature": {
                "name": "温度表0工作温度",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_temp1_comm_efficiency": {
                "name": "温度表1通信效率",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_temp1_battery_voltage": {
                "name": "温度表1电池电压",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_temp1_sleep_time": {
                "name": "温度表1休眠时间",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_temp1_status": {
                "name": "温度表1仪表状态",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_temp1_value": {
                "name": "温度表1温度值",
                "unit": "",
                "type": "float32",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_temp1_battery_remain": {
                "name": "温度表1电池剩余时间",
                "unit": "",
                "type": "float32",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_temp1_work_temperature": {
                "name": "温度表1工作温度",
                "unit": "",
                "type": "int16",
                "category": "temperature",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_dynamometer_comm_efficiency": {
                "name": "示功仪通信效率",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_dynamometer_battery_voltage": {
                "name": "示功仪电池电压",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x1",
            },
            "g7_dynamometer_sleep_time": {
                "name": "示功仪休眠时间",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_dynamometer_status": {
                "name": "示功仪仪表状态",
                "unit": "",
                "type": "int16",
                "category": "status",
                "min": 0, "max": 9999,
                "register_addr": "0x2",
            },
            "g7_dynamometer_battery_remain": {
                "name": "示功仪电池剩余时间",
                "unit": "",
                "type": "float32",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x4",
            },
            "g7_running_frequency": {
                "name": "运行频率",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9dd4",
            },
        }
    },
    "oilfield_g8": {
        "product_name": "仪表扩展 (G8)",
        "points": {
            "g8_power_freq_vfd_switch": {
                "name": "工变频切换",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e66",
            },
            "g8_range_1": {
                "name": "范围1",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e67",
            },
            "g8_range_2": {
                "name": "范围2",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e68",
            },
            "g8_upper_avg_power_a": {
                "name": "上平均功率a",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e69",
            },
            "g8_lower_avg_power_a": {
                "name": "下平均功率a",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e6a",
            },
            "g8_power_balance_a": {
                "name": "功率平衡度a",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e6b",
            },
            "g8_current_stroke_freq": {
                "name": "当前冲次",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e6c",
            },
            "g8_upper_max_current_a": {
                "name": "上最大电流a",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e6e",
            },
            "g8_lower_max_current_a": {
                "name": "下最大电流a",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e70",
            },
            "g8_current_balance_a": {
                "name": "电流平衡度a",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e73",
            },
            "g8_active_power": {
                "name": "有功功率",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e74",
            },
            "g8_forward_reverse": {
                "name": "正反转",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e75",
            },
            "g8_rated_power": {
                "name": "额定功率",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e76",
            },
            "g8_rated_voltage": {
                "name": "额定电压",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e77",
            },
            "g8_rated_current": {
                "name": "额定电流",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e78",
            },
            "g8_rated_frequency": {
                "name": "额定频率",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e79",
            },
            "g8_stroke_freq_setpoint": {
                "name": "冲次给定",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e7a",
            },
            "g8_continuous_pumping_time": {
                "name": "连续抽油时间",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e7b",
            },
            "g8_swing_mode_selection": {
                "name": "打摆方式选择",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e7c",
            },
            "g8_continuous_swing_time": {
                "name": "连续打摆时间",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e7d",
            },
            "g8_swing_switch_loss_action": {
                "name": "打摆开关丢失动作",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e7e",
            },
            "g8_intermittent_pumping_mode": {
                "name": "间抽功能选择",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e7f",
            },
            "g8_free_swing_angle": {
                "name": "自由打摆角度",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e80",
            },
            "g8_data_save_interval": {
                "name": "数据存盘时间",
                "unit": "",
                "type": "int16",
                "category": "electrical",
                "min": 0, "max": 9999,
                "register_addr": "0x9e81",
            },
        }
    },
