-- ============================================================
-- A11 逆向验证脚本 — Oracle 端 (只读, 不影响生产)
-- 当 Oracle 恢复后执行: sqlplus user/pass@192.168.10.129:1521/db @validate_oracle.sql
-- ============================================================

SET PAGESIZE 200
SET LINESIZE 300

-- 1. 验证表结构是否匹配
SELECT '=== L3: 表结构验证 ===' FROM DUAL;

-- 排水井表 (预期字段: PSJID, RTUHISTIME, ZYL, ZSYL1, SSZS1, LJZS1...)
SELECT 'psj_cols' AS tbl, COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME LIKE '%PSJ%' OR TABLE_NAME LIKE '%47015%'
ORDER BY TABLE_NAME, COLUMN_ID;

-- 计量间表 (预期字段: JLJID, RTUHistime, JLJGH, JLJSSJ...)
SELECT 'jlj0_cols' AS tbl, COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME LIKE '%JLJ%' OR TABLE_NAME LIKE '%47016%'
ORDER BY TABLE_NAME, COLUMN_ID;

-- 2. 验证数据格式 (抽5行)
SELECT '=== L3: 数据格式验证 ===' FROM DUAL;
SELECT * FROM (
  SELECT PSJID, RTUHISTIME, ZYL, ZSYL1, SSZS1, LJZS1 FROM (
    SELECT PSJID, RTUHISTIME, ZYL, ZSYL1, SSZS1, LJZS1,
           ROW_NUMBER() OVER (ORDER BY RTUHISTIME DESC) rn
    FROM (
      SELECT PSJID, RTUHISTIME, ZYL, ZSYL1, SSZS1, LJZS1
      FROM (SELECT * FROM ALL_TABLES WHERE TABLE_NAME LIKE '%PSJ%' OR TABLE_NAME LIKE '%47015%')
    )
  ) p WHERE rn <= 5
);

-- 3. 验证测点数量 (预期: 排水井13个/计量间13-25个)
SELECT '=== L4: 测点验证 ===' FROM DUAL;
SELECT COUNT(*) AS psj_rows FROM (
  SELECT 1 FROM ALL_TABLES WHERE TABLE_NAME LIKE '%PSJ%' OR TABLE_NAME LIKE '%47015%'
);

-- 4. 对比: 提取与逆向一致的字段名
SELECT 'EXPECTED: PSJID,RTUHISTIME,ZYL,ZSYL1,SSZS1,LJZS1,ZSYL2,SSZS2,LJZS2,ZSYL3,SSZS3,LJZS3' FROM DUAL;
SELECT 'EXPECTED: JLJID,RTUHistime,JLJGH,JLJSSJ,YXF,YXM,JLGC,JLFS,RCYE_F,RCYE_D,RCY_F,RCY_D,RCS' FROM DUAL;
SELECT 'EXPECTED: JLJID,RTUHistime,SCHGYL,SCHGWD,JLFLQCKYL,JLFLYGLL,JLFLYW,JLFLJKWD,JLQGXDLL,JLQGXX' FROM DUAL;
