<template><div class="page"><h3 style="color:#c0d5e8;margin:0 0 12px">🧬 算法市场</h3>
<el-row :gutter="12"><el-col :span="8" v-for="a in algorithms" :key="a.id"><el-card shadow="hover" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between"><span style="font-weight:bold;font-size:15px">{{ a.name }}</span><el-tag :type="a.status==='approved'?'success':'warning'" size="small">{{ a.status==='approved'?'已审核':'审核中' }}</el-tag></div><div style="font-size:12px;color:#909399;margin:6px 0">{{ a.scene }}</div><el-descriptions :column="2" size="small" border><el-descriptions-item label="提交">{{ a.author }}</el-descriptions-item><el-descriptions-item label="效果">{{ a.effect }}%</el-descriptions-item><el-descriptions-item label="下载">{{ a.downloads }}</el-descriptions-item><el-descriptions-item label="评分">{{ '⭐'.repeat(Math.round(a.rating)) }}</el-descriptions-item></el-descriptions><div style="margin-top:8px;display:flex;gap:4px"><el-button size="small" type="primary" @click="deploy(a)">部署</el-button><el-button size="small" @click="preview(a)">预览</el-button></div></el-card></el-col></el-row>
<div style="margin-top:12px"><el-button type="success" @click="showUpload=true">+ 提交新算法</el-button></div>
<el-dialog v-model="showUpload" title="提交定制算法" width="500px"><el-form label-width="80px" size="small"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="适用场景"><el-input v-model="form.scene"/></el-form-item><el-form-item label="代码文件"><el-upload action="/api/algorithm/upload"><el-button size="small">上传 .py</el-button></el-upload></el-form-item></el-form><template #footer><el-button @click="showUpload=false">取消</el-button><el-button type="primary" @click="submit">提交审核</el-button></template></el-dialog></div></template>
<script setup>import { ref,onMounted } from 'vue';import api from '../api';import { ElMessage } from 'element-plus'
const algorithms=ref([{id:'a1',name:'泵效诊断',scene:'抽油机井',author:'第四作业区',effect:92.5,downloads:15,rating:4.5,status:'approved'},{id:'a2',name:'动液面计算',scene:'抽油机井',author:'第三作业区',effect:89.1,downloads:8,rating:4.2,status:'approved'},{id:'a3',name:'含水率趋势',scene:'电泵井',author:'第二作业区',effect:0,downloads:0,rating:0,status:'pending'}])
const showUpload=ref(false);const form=ref({name:'',scene:''})
const deploy=a=>ElMessage.success(`部署 ${a.name}`)
const preview=a=>ElMessage.info(`预览 ${a.name}`)
const submit=()=>{algorithms.value.push({id:'a'+Date.now(),name:form.value.name,scene:form.value.scene,author:'本地',effect:0,downloads:0,rating:0,status:'pending'});showUpload.value=false;ElMessage.success('已提交审核')}
onMounted(async()=>{try{const r=await api.get('/algorithm/market');algorithms.value=r.algorithms||algorithms.value}catch{}})
</script>
