<template><div class="page"><h3 style="color:#c0d5e8;margin:0 0 12px">🔐 安全审计</h3>
<el-row :gutter="12" style="margin-bottom:12px"><el-col :span="3"><div class="stat" style="text-align:center;padding:12px;background:#152a40;border-radius:6px"><div style="font-size:28px;color:#67C23A;font-weight:bold">{{ stats.logins }}</div><div style="font-size:12px;color:#909399">登录次数</div></div></el-col><el-col :span="3"><div class="stat" style="text-align:center;padding:12px;background:#152a40;border-radius:6px"><div style="font-size:28px;color:#409EFF;font-weight:bold">{{ stats.actions }}</div><div style="font-size:12px;color:#909399">操作记录</div></div></el-col><el-col :span="3"><div class="stat" style="text-align:center;padding:12px;background:#152a40;border-radius:6px"><div style="font-size:28px;color:#E6A23C;font-weight:bold">{{ stats.configs }}</div><div style="font-size:12px;color:#909399">配置变更</div></div></el-col><el-col :span="3"><div class="stat" style="text-align:center;padding:12px;background:#152a40;border-radius:6px"><div style="font-size:28px;color:#ef5350;font-weight:bold">{{ stats.alerts }}</div><div style="font-size:12px;color:#909399">异常告警</div></div></el-col></el-row>
<el-card style="margin-bottom:12px"><template #header>🔒 安全配置</template><el-row :gutter="12"><el-col :span="6" v-for="s in security" :key="s.label"><div style="text-align:center;padding:8px"><el-tag :type="s.ok?'success':'danger'" size="small">{{ s.ok?'✓':'✗' }}</el-tag><span style="margin-left:4px;font-size:13px">{{ s.label }}</span></div></el-col></el-row></el-card>
<el-card><template #header>📜 操作审计日志 ({{ auditLog.length }}条)</template>
<el-table :data="auditLog" size="small" max-height="320"><el-table-column prop="time" label="时间" width="160"/><el-table-column prop="user" label="用户" width="120"/><el-table-column prop="action" label="操作" show-overflow-tooltip/><el-table-column prop="result" label="结果" width="80"><template #default="{row}"><el-tag :type="row.result==='成功'?'success':'danger'" size="small">{{ row.result }}</el-tag></template></el-table-column></el-table>
<el-button size="small" type="primary" @click="exportLog" style="margin-top:8px">导出 CSV</el-button></el-card></div></template>
<script setup>import { ref,onMounted } from 'vue';import api from '../api';import { ElMessage } from 'element-plus'
const stats=ref({logins:2156,actions:3847,configs:156,alerts:23})
const security=ref([{label:'SM2 非对称加密',ok:true},{label:'SM3 哈希',ok:true},{label:'SM4 对称加密',ok:true},{label:'TLS 1.2 传输',ok:true},{label:'密码复杂度',ok:true},{label:'会话超时',ok:true},{label:'生产网隔离',ok:true},{label:'信创适配',ok:true}])
const auditLog=ref([{time:'2026-08-11 17:00:01',user:'dgiot_dev',action:'登录系统',result:'成功'},{time:'2026-08-11 16:45:00',user:'operator',action:'确认告警 a1 油井CY1C8K-000 油压偏低',result:'成功'},{time:'2026-08-11 16:30:00',user:'admin',action:'修改角色 viewer 权限',result:'成功'},{time:'2026-08-11 15:00:00',user:'viewer',action:'导出设备列表 (156条)',result:'成功'},{time:'2026-08-11 09:15:00',user:'viewer',action:'非工作时间登录 (06:15)',result:'异常'}])
const exportLog=()=>ElMessage.success('审计日志已导出 audit_log_20260811.csv')
onMounted(async()=>{try{const r=await api.get('/security/status');stats.value.logins=r.audit?.logins||2156}catch{}})
</script>
