const provider = [
  {
    name: 'username',
    value: 'username',
    caption: 'username',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
  {
    name: 'id',
    value: 'id',
    caption: 'id',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
  {
    name: 'payload',
    value: 'payload',
    caption: 'payload',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
  {
    name: 'qos',
    value: 'qos',
    caption: 'qos',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
  {
    name: 'timestamp',
    value: 'timestamp',
    caption: 'timestamp',
    meta: 'timestamp',
    type: 'dgiot',
    score: 1000,
  },
  {
    name: 'topic',
    value: 'topic',
    caption: 'topic',
    meta: 'topic',
    type: 'dgiot',
    score: 1000,
  },
  {
    name: 'node',
    value: 'node',
    caption: 'node',
    meta: 'node',
    type: 'dgiot',
    score: 1000,
  },
  {
    name: '"$events/message_delivered"',
    value: '"$events/message_delivered"',
    caption: '"$events/message_delivered"',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
  {
    name: '"$events/message_acked"',
    value: '"$events/message_acked"',
    caption: '"$events/message_acked"',
    meta: 'dgiot',
    type: '"$events/message_acked"',
    score: 1000,
  },
  {
    name: '"$events/message_dropped"',
    value: '"$events/message_dropped"',
    caption: '"$events/message_dropped"',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
  {
    name: '"$events/client_connected"',
    value: '"$events/client_connected"',
    caption: '"$events/client_connected"',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
  {
    name: '"$events/client_disconnected"',
    value: '"$events/client_disconnected"',
    caption: '"$events/client_disconnected"',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
  {
    name: '"$events/session_subscribed"',
    value: '"$events/session_subscribed"',
    caption: '"$events/session_subscribed"',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
  {
    name: '"$events/session_unsubscribed"',
    value: '"$events/session_unsubscribed"',
    caption: '"$events/session_unsubscribed"',
    meta: 'dgiot',
    type: 'local',
    score: 1000,
  },
]
export default provider
